[build]
  publish = "public"
  command = "composer install && php bin/console cache:clear --env=prod"

[context.production.environment]
  PHP_VERSION = "8.1"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true
