name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama que estás usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Puedes cambiar a la versión de PHP que necesites

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Build the site
        run: php bin/console cache:clear --env=prod

      # - name: Build the static site
      #   run: php bin/console your:build:command # Reemplaza este comando por el que uses para construir tu sitio estático

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Cambia './public' por tu directorio de build si es diferente

